import requests

seq = "MASPSLPGSDCSQIIDHSHVPEFEVATWIKITLILVYLIIFVMGLLGNSATIRVTQVLQKKGYLQKEVTDHMVSLACSDILVFLIGMPMEFYSIIWNPLTTSSYTLSCKLHTFLFEACSYATLLHVLTLSFERYIAICHPFRYKAVSGPCQVKLLIGFVWVTSALVALPLLFAMGTEYPLVNVPSHRGLTCNRSSTRHHEQPETSNMSICTNLSSRWTVFQSSIFGAFVVYLVVLLSVAFMCWNMMQVLMKSQKGSLAGGTRPPQLRKSESEESRTARRQTIIFLRLIVVTLAVCWMPNQIRRIMAAAKPKHDWTRSYFRAYMILLPFSETFFYLSSVINPLLYTVSSQQFRRVFVQVLCCRLSLQHANHEKRLRVHAHSTTDSARFVQRPLLFASRRQSSARRTEKIFLSTFQSEAEPQSKSQSLSLESLEPNSGAKPANSAAENGFQEHEV"
url = "https://api.esmatlas.com/foldSequence/v1/pdb/"
seq=seq[:400]
response = requests.post(url, data=seq)
with open("Structure_Agent/result.pdb", "w") as f:
    f.write(response.text)

print("✅ PDB结构预测完成，已保存 result.pdb")

import biotite.structure.io as bsio
struct = bsio.load_structure("Structure_Agent/result.pdb", extra_fields=["b_factor"])
print(struct.b_factor.mean())  # this will be the pLDDT
# 88.3
